service: bitcoin-exchange
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  averageTickers:
    handler: averageTickers.handle
    events:
      - http:
          path: averageTickers
          method: get
  sendTickersViaEmail:
    handler: sendTickersViaEmail.handle
    events:
      - http:
          path: sendTickersViaEmail
          method: post
